# -*- coding: utf-8 -*-
"""Untitled8.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1NMf7HLOAZzdO6j7UwFMV8puIn3Kh69ix
"""

test = 'Www.HackerRank.com'

test_list = list(test)
for c,v in enumerate(test_list):
  if test_list[c].isupper():
    test_list[c] = v.lower()
  else:
    test_list[c] = v.upper()

test_str = ''.join(test_list)
print(test_str)